### ISSUE TITLE
32 bit binary

### ISSUE THREAD

**Issue by klamann** [jackra1n/RustBerry-PoE-Monitor#2]
currently there is only one binary available for aarch64. Even though 64 bit CPUs have been available since the Raspberry Pi 3, the official Raspberry Pi OS still distributes the 32 bit OS as the default and the binary will silently fail on a 32 bit linux. 

Can you provide a 32 bit build, or make it clear that this is a 64 bit build and maybe check for OS architecture in the install script?

**Comment by jackra1n** [comment]
Thanks for the report! That's a very good point! Did not think about it as I always try to use 64bit when possible. Will try to add 32bit version ASAP! 🙂

**Comment by jackra1n** [comment]
Hi @klamann I added a 32bit binary and improved the install script which should automatically install the right version depending on your OS. Let me know if you have any issues 🙂

**Comment by klamann** [comment]
works great, thanks!
